import { icons } from './icons.js';
import { t } from './i18n.js';

const ctx=()=>{try{return window.SillyTavern?.getContext?.()||null}catch(_){return null}};
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
export class HealthPanel{
 constructor(toast,getSnapshot){this.toast=toast;this.getSnapshot=getSnapshot;this.root=null;}
 mount(){this.ensure()}
 unmount(){this.root?.remove();this.root=null}
 open(){this.ensure();this.root.hidden=false;this.render();requestAnimationFrame(()=>this.root?.classList.add('is-open'))}
 close(){if(!this.root)return;this.root.classList.remove('is-open');setTimeout(()=>{if(this.root&&!this.root.classList.contains('is-open'))this.root.hidden=true},160)}
 ensure(){if(this.root=document.querySelector('#nt-health-panel'))return this.root;const r=document.createElement('div');r.id='nt-health-panel';r.hidden=true;r.innerHTML=`<div class="nt-tool-backdrop" data-nt-health-close></div><section class="nt-tool-modal nt-health-modal"><header class="nt-tool-header"><div><span>${icons.health}</span><div><b>${t('Health & Performance')}</b><small>${t('Diagnostics for SillyTavern and NastyTavern')}</small></div></div><div><button data-nt-health-refresh>${icons.refresh}</button><button data-nt-health-close>${icons.close}</button></div></header><div data-nt-health-body class="nt-health-body"></div><footer><button data-nt-health-copy>${icons.copy}<span>${t('Copy diagnostic report')}</span></button></footer></section>`;r.addEventListener('click',e=>{if(e.target.closest('[data-nt-health-close]'))this.close();if(e.target.closest('[data-nt-health-refresh]'))this.render();if(e.target.closest('[data-nt-health-copy]'))this.copy()});document.body.append(r);this.root=r;return r;}
 snapshot(){const c=ctx(),extra=this.getSnapshot?.()||{};const selectors={'Chat':'#chat','Composer':'#send_form','Characters':'#right-nav-panel','Personas':'#PersonaManagement','World Info':'#WorldInfo','Advanced Formatting':'#AdvancedFormatting'};return {stVersion:document.querySelector('#version_display')?.textContent?.trim()||'Unknown',nastyVersion:'0.1.2',view:document.body?.dataset?.mtView||'chat',chatId:c?.getCurrentChatId?.()||c?.chatId||'',messages:Array.isArray(c?.chat)?c.chat.length:0,dom:document.getElementsByTagName('*').length,extensions:Object.keys(c?.extensionSettings||{}).length,localVars:Object.keys(c?.chatMetadata?.variables||{}).length,globalVars:Object.keys(c?.extensionSettings?.variables?.global||{}).length,selectors:Object.fromEntries(Object.entries(selectors).map(([k,s])=>[k,!!document.querySelector(s)])),...extra};}
 render(){const s=this.snapshot(),body=this.root?.querySelector('[data-nt-health-body]');if(!body)return;const metric=(name,val)=>`<article><span>${esc(t(name))}</span><b>${esc(val)}</b></article>`;body.innerHTML=`<section><h3>${t('Runtime')}</h3><div class="nt-health-grid">${metric('SillyTavern',s.stVersion)}${metric('NastyTavern',s.nastyVersion)}${metric('Active view',s.view)}${metric('Chat',s.chatId||t('None'))}</div></section><section><h3>${t('Performance')}</h3><div class="nt-health-grid">${metric('Messages loaded',s.messages)}${metric('DOM elements',s.dom.toLocaleString())}${metric('Extension settings namespaces',s.extensions)}${metric('Timeline nodes',s.timelineNodes||0)}${metric('Context tokens',s.contextTokens||0)}${metric('Context usage',`${s.contextPercent||0}%`)}</div></section><section><h3>${t('State')}</h3><div class="nt-health-grid">${metric('Active World Info entries',s.worldInfoEntries||0)}${metric('Local variables',s.localVars)}${metric('Global variables',s.globalVars)}${metric('Bookmarks',s.bookmarks||0)}${metric('Session notes',s.notes||0)}${metric('Calendar events',s.calendarEvents||0)}${metric('Weekly schedule items',s.weeklyItems||0)}</div></section><section><h3>${t('Selector health')}</h3><div class="nt-health-selectors">${Object.entries(s.selectors).map(([k,v])=>`<span class="${v?'is-ok':'is-bad'}">${v?'✓':'×'} ${esc(k)}</span>`).join('')}</div></section>`;}
 async copy(){const s=this.snapshot();const text=`NastyTavern diagnostic\n${JSON.stringify(s,null,2)}`;try{await navigator.clipboard.writeText(text);this.toast?.(t('Diagnostic report copied.'))}catch(_){this.toast?.(t('Could not copy diagnostic report.'))}}
}
