import { icons } from './icons.js';
import { t } from './i18n.js';
import { defaults, saveSettings, applySettings } from './settings.js';

const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const modifierKeys=new Set(['Shift','Control','Alt','Meta']);
const browserReserved=new Set(['Ctrl+K','Ctrl+L','Ctrl+T','Ctrl+N','Ctrl+W','Ctrl+R','Ctrl+Shift+T','Ctrl+Shift+N','Ctrl+Shift+W','Ctrl+Shift+R','Ctrl+Shift+B','Ctrl+Shift+C','Ctrl+Shift+I','Ctrl+Shift+J','Ctrl+Shift+O','Ctrl+Shift+P','Ctrl+Shift+Delete','F5','F12']);

export class PreferencesManager{
 constructor(settings,toast,callbacks){this.settings=settings;this.toast=toast;this.callbacks=callbacks;this.root=null;this.tab='backup';this.recording=null;this.boundCaptureKeydown=e=>this.captureShortcut(e);this.boundCaptureKeyup=e=>this.captureKeyup(e);this.boundCaptureBlur=()=>this.cancelRecording();}
 mount(){this.ensure();}
 unmount(){this.cancelRecording(false);this.root?.remove();this.root=null;}
 open(tab='backup'){this.ensure();this.tab=tab;this.root.hidden=false;this.render();requestAnimationFrame(()=>this.root?.classList.add('is-open'));}
 close(){this.cancelRecording(false);if(!this.root||this.root.hidden)return;this.root.classList.remove('is-open');setTimeout(()=>{if(this.root&&!this.root.classList.contains('is-open'))this.root.hidden=true},160);}
 ensure(){if(this.root=document.querySelector('#nt-preferences'))return this.root;const r=document.createElement('div');r.id='nt-preferences';r.hidden=true;r.innerHTML=`<div class="nt-tool-backdrop" data-nt-pref-close></div><section class="nt-tool-modal nt-pref-modal"><header class="nt-tool-header"><div><span>${icons.workspace}</span><div><b>${t('NastyTavern Settings')}</b><small>${t('Backup, modules and keyboard shortcuts')}</small></div></div><button data-nt-pref-close>${icons.close}</button></header><div class="nt-tool-tabs"><button data-nt-pref-tab="backup">${t('Backup & Restore')}</button><button data-nt-pref-tab="modules">${t('Modules')}</button><button data-nt-pref-tab="shortcuts">${t('Keyboard Shortcuts')}</button></div><div data-nt-pref-body class="nt-pref-body"></div><input type="file" accept="application/json,.json" data-nt-pref-import hidden></section>`;r.addEventListener('click',e=>this.onClick(e));r.addEventListener('change',e=>this.onChange(e));r.querySelector('[data-nt-pref-import]').addEventListener('change',e=>this.importFile(e.target.files?.[0]));document.body.append(r);this.root=r;return r;}
 render(){if(!this.root)return;if(!['backup','modules','shortcuts'].includes(this.tab))this.tab='backup';this.root.querySelectorAll('[data-nt-pref-tab]').forEach(b=>b.classList.toggle('is-active',b.dataset.ntPrefTab===this.tab));const body=this.root.querySelector('[data-nt-pref-body]');if(this.tab==='shortcuts')return body.innerHTML=this.renderShortcuts();if(this.tab==='modules')return body.innerHTML=this.renderModules();body.innerHTML=this.renderBackup();}
 renderBackup(){return `<div class="nt-pref-backup"><article><span>${icons.download}</span><div><b>${t('Export NastyTavern settings')}</b><p>${t('Export appearance, shortcuts and module preferences.')}</p></div><button data-nt-pref-export>${t('Export')}</button></article><article><span>${icons.upload}</span><div><b>${t('Import NastyTavern settings')}</b><p>${t('Restore a previously exported NastyTavern JSON file.')}</p></div><button data-nt-pref-import-trigger>${t('Import')}</button></article></div>`;}
 renderModules(){const modules=this.settings.modules||defaults.modules;const defs=[
  ['timeline',t('Story Timeline'),t('Timeline and branching conversation viewer.'),icons.timeline],
  ['contextInspector',t('Context / Token Inspector'),t('Prompt composition and context usage inspector.'),icons.inspector],
  ['worldInfoInspector',t('World Info Inspector'),t('Activated Lorebook entries, live scan and history.'),icons.lore],
  ['variables',t('Variable Manager'),t('Local and global variable manager.'),icons.variables],
  ['chatTools',t('Bookmarks & Notes'),t('Per-chat bookmarks and private session notes.'),icons.bookmark],
  ['calendar',t('Calendar & Schedule'),t('Story calendar, events and schedule tools.'),icons.calendar],
  ['community',t('Community Chat'),t('Real-time community chat powered by Supabase.'),icons.community],
];return `<div class="nt-pref-modules"><div class="nt-pref-section-head"><div><b>${t('NastyTavern Modules')}</b><small>${t('Choose which integrated tools are shown in the Nasty Chat Bar.')}</small></div></div><div class="nt-pref-module-grid">${defs.map(([id,label,hint,icon])=>`<label class="nt-pref-module-card"><span class="nt-pref-module-icon">${icon}</span><span class="nt-pref-module-copy"><b>${esc(label)}</b><small>${esc(hint)}</small></span><input type="checkbox" data-nt-module-visible="${esc(id)}" ${modules[id]!==false?'checked':''}></label>`).join('')}</div><p class="nt-shortcut-help">${t('Hidden modules stay installed and can still be opened with their keyboard shortcut or the Command Palette.')}</p></div>`;}
 renderShortcuts(){const defs=this.callbacks.getShortcutDefinitions?.()||[];const groups=[];for(const d of defs){const name=d.group||'NastyTavern';let group=groups.find(x=>x.name===name);if(!group){group={name,items:[]};groups.push(group);}group.items.push(d);}const rows=groups.map(group=>`<section class="nt-shortcut-group"><div class="nt-shortcut-group-title">${esc(t(group.name))}</div>${group.items.map(d=>`<article><div><b>${esc(t(d.label))}</b><small>${esc(t(d.hint||''))}</small></div><button class="nt-shortcut-record ${this.recording===d.id?'is-recording':''}" data-nt-shortcut="${esc(d.id)}">${esc(this.recording===d.id?t('Press shortcut…'):(this.settings.shortcuts?.[d.id]||t('Unassigned')))}</button></article>`).join('')}</section>`).join('');return `<div class="nt-shortcuts"><div class="nt-pref-section-head"><div><b>${t('Keyboard Shortcuts')}</b><small>${t('Click a shortcut and press the new key combination.')}</small></div><button data-nt-pref-reset-shortcuts>${t('Reset')}</button></div>${rows}<p class="nt-shortcut-help">${t('Duplicate shortcuts are rejected automatically.')} ${t('Press Backspace or Delete while recording to clear a shortcut.')} ${t('Some browser shortcuts cannot be overridden.')}</p></div>`;}
 onChange(e){const toggle=e.target.closest('[data-nt-module-visible]');if(!toggle)return;const id=toggle.dataset.ntModuleVisible;this.settings.modules??=structuredClone(defaults.modules);this.settings.modules[id]=!!toggle.checked;applySettings(this.settings);saveSettings();this.callbacks.modulesChanged?.();}
 async onClick(e){if(e.target.closest('[data-nt-pref-close]'))return this.close();const tab=e.target.closest('[data-nt-pref-tab]');if(tab){this.cancelRecording(false);this.tab=tab.dataset.ntPrefTab;return this.render();}if(e.target.closest('[data-nt-pref-export]'))return this.exportSettings();if(e.target.closest('[data-nt-pref-import-trigger]'))return this.root.querySelector('[data-nt-pref-import]').click();if(e.target.closest('[data-nt-pref-reset-shortcuts]')){this.cancelRecording(false);this.settings.shortcuts=structuredClone(defaults.shortcuts);saveSettings();this.callbacks.shortcutsChanged?.();return this.render();}const rec=e.target.closest('[data-nt-shortcut]');if(rec)return this.startRecording(rec.dataset.ntShortcut);}
 startRecording(id){this.cancelRecording(false);this.recording=id;this.render();window.addEventListener('keydown',this.boundCaptureKeydown,true);window.addEventListener('keyup',this.boundCaptureKeyup,true);window.addEventListener('blur',this.boundCaptureBlur,true);}
 cancelRecording(render=true){window.removeEventListener('keydown',this.boundCaptureKeydown,true);window.removeEventListener('keyup',this.boundCaptureKeyup,true);window.removeEventListener('blur',this.boundCaptureBlur,true);const had=!!this.recording;this.recording=null;if(render&&had)this.render();}
 captureKeyup(e){if(!this.recording)return;e.preventDefault();e.stopImmediatePropagation();}
 captureShortcut(e){if(!this.recording)return;e.preventDefault();e.stopImmediatePropagation();const id=this.recording;if(['Backspace','Delete'].includes(e.key)){this.settings.shortcuts??={};this.settings.shortcuts[id]='';saveSettings();this.callbacks.shortcutsChanged?.();this.cancelRecording(false);this.render();return;}if(e.key==='Escape'){this.cancelRecording(false);this.render();return;}if(modifierKeys.has(e.key)){this.updateRecordingPreview(e);return;}const combo=this.callbacks.eventToShortcut?.(e)||'';if(!combo)return;if(browserReserved.has(combo)){this.toast?.(t('This shortcut is reserved by the browser. Choose another combination.'));this.updateRecordingPreview(e,true);return;}const duplicate=Object.entries(this.settings.shortcuts||{}).find(([k,v])=>k!==id&&v===combo);if(duplicate){this.toast?.(t('Shortcut already assigned.'));this.updateRecordingPreview(e,true);return;}this.settings.shortcuts??={};this.settings.shortcuts[id]=combo;saveSettings();this.callbacks.shortcutsChanged?.();this.cancelRecording(false);this.render();}
 updateRecordingPreview(e,error=false){const button=this.root?.querySelector(`[data-nt-shortcut="${CSS.escape(this.recording||'')}"]`);if(!button)return;const parts=[];if(e.ctrlKey||e.metaKey)parts.push('Ctrl');if(e.altKey)parts.push('Alt');if(e.shiftKey)parts.push('Shift');button.textContent=parts.length?`${parts.join('+')}+…`:t('Press shortcut…');button.classList.toggle('is-error',!!error);}
 exportSettings(){const safe={};for(const k of Object.keys(defaults))safe[k]=structuredClone(this.settings[k]);const blob=new Blob([JSON.stringify({format:'NastyTavern-settings',version:1,settings:safe},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='nastytavern-settings.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
 async importFile(file){if(!file)return;try{const parsed=JSON.parse(await file.text());if(parsed?.format!=='NastyTavern-settings'||!parsed.settings)throw new Error('invalid');for(const k of Object.keys(defaults))if(Object.hasOwn(parsed.settings,k))this.settings[k]=parsed.settings[k];applySettings(this.settings);saveSettings();this.callbacks.shortcutsChanged?.();this.toast?.(t('NastyTavern settings imported.'));this.render();}catch(_){this.toast?.(t('Invalid NastyTavern settings file.'));}finally{this.root.querySelector('[data-nt-pref-import]').value='';}}
}
